apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nats-monitoring
  namespace: nats
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
    kubernetes.io/ingress.class: "gce"
spec:
  tls:
    - hosts:
        - nats.example.com
      secretName: nats-monitoring-tls
  rules:
    - host: nats.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: nats-headless
                port:
                  number: 8222
