apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: nats-monitoring
  namespace: nats-minimal
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-staging
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
spec:
  ingressClassName: nginx
  tls:
  - hosts:
    - nats.example.com  # Patched by kustomize
    secretName: nats-monitoring-tls
  rules:
  - host: nats.example.com  # Patched by kustomize
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: nats
            port:
              number: 8222
