apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- cluster-secret-store.yaml

# Patch the project ID in the ClusterSecretStore
patches:
- target:
    kind: ClusterSecretStore
    name: gcpsm-cluster-store
  patch: |-
    - op: replace
      path: /spec/provider/gcpsm/projectID
      value: erik-sandbox-408216
