apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
- namespace.yaml
- provider-gcp.yaml
- provider-config.yaml

# Patch the project ID in the ProviderConfig
patches:
- target:
    kind: ProviderConfig
    name: default
  patch: |-
    - op: replace
      path: /spec/projectID
      value: erik-sandbox-408216
