apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - namespace.yaml
  - service.yaml
  - pvc.yaml
  - ingress.yaml
  - certificate.yaml
  - deployment.yaml
  - configmap.yaml
  - secret-generator-rbac.yaml
  - kms-key-generator.yaml
  - kms-externalsecret.yaml
  - postgres-password-generator.yaml
  - postgres-password-externalsecret.yaml
  - postgres.yaml
  - db-client-cert-job.yaml
  - postgres-dsn-job.yaml
  - image-pull-secret.yaml
